name: Test

on:
  workflow_call:
  pull_request:
    branches: ["main"]

jobs:
  app-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: phpcs
      - uses: actions/checkout@v4
      - name: Install PHP Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Execute tests via PHPUnit
        run: php artisan test
