name: Test

on:
  workflow_call:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: phpcs
      - uses: actions/checkout@v4
      - name: Install PHP Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Execute tests via PHPUnit
        run: composer test

  coverage:
    needs: [test]
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install PHP Dependencies
        run: sudo pecl install xdebug && docker-php-ext-enable xdebug
          && curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          && chmod +x ./cc-test-reporter
      - name: run coverage analysis
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: ./cc-test-reporter before-build && vendor/bin/phpunit --coverage-clover clover.xml && ./cc-test-reporter after-build -t clover --exit-code $?
